### ISSUE TITLE
Assertion failed on "assert len(amr.nodes) == len(concept) == len(amr.node_values)"

### ISSUE THREAD

**Issue by wenchaodudu** [Sean-Blank/AMRcoref#2]
I used penman 0.6.0 do run prepare_data.py

Then when I ran preprocess.py, I got:

`Traceback (most recent call last):
  File "preprocess.py", line 354, in <module>
    item = pre_to_json(data_per_doc, links_per_doc, file_name)
  File "preprocess.py", line 307, in pre_to_json
    data, cluster = get_clusters_info(links, data)
  File "preprocess.py", line 260, in get_clusters_info
    pdb.set_trace()
  File "preprocess.py", line 240, in mapping_edges
    assert len(amr.nodes) == len(concept) == len(amr.node_values)
AssertionError
`

**Comment by Sean-Blank** [comment]
you can try penman 1.2, i am not sure 0.6.0 is ok.

**Comment by wenchaodudu** [comment]
I tried penman 1.2 then I got this error when running prepare_data.py
`False
Traceback (most recent call last):
  File "prepare_data.py", line 8, in <module>
    from amr_parsing.io import AMRIO
  File "/vc_data/users/wenchaodu/AMRcoref/amr_parsing/io.py", line 3, in <module>
    from amr_parsing.amr import AMR, AMRGraph
  File "/vc_data/users/wenchaodu/AMRcoref/amr_parsing/amr.py", line 18, in <module>
    penman.AMRCodec._inversions.pop('domain')
AttributeError: module 'penman' has no attribute 'AMRCodec'
`

**Comment by Sean-Blank** [comment]
> I tried penman 1.2 then I got this error when running prepare_data.py
> `False Traceback (most recent call last): File "prepare_data.py", line 8, in <module> from amr_parsing.io import AMRIO File "/vc_data/users/wenchaodu/AMRcoref/amr_parsing/io.py", line 3, in <module> from amr_parsing.amr import AMR, AMRGraph File "/vc_data/users/wenchaodu/AMRcoref/amr_parsing/amr.py", line 18, in <module> penman.AMRCodec._inversions.pop('domain') AttributeError: module 'penman' has no attribute 'AMRCodec' `

It seems to be a version problem of other packages, I will check it again and update the re.txt

**Comment by wenchaodudu** [comment]
Can you please send me a copy of preprocessed data? We have the appropriate LDC license.

**Comment by Sean-Blank** [comment]
> Can you please send me a copy of preprocessed data? We have the appropriate LDC license.

Sorry, maybe I sent it to the wrong address before. Please check your email again.

**Comment by wenchaodudu** [comment]
Are you sending it to my email at duwc2013@gmail.com?
